Name:           ros-melodic-pr2eus
Version:        0.3.14
Release:        3%{?dist}
Summary:        ROS pr2eus package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2eus
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-control-msgs
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-euscollada
Requires:       ros-melodic-move-base-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-pr2-controllers-msgs
Requires:       ros-melodic-pr2-description
Requires:       ros-melodic-pr2-mechanism-msgs
Requires:       ros-melodic-pr2-msgs
Requires:       ros-melodic-roseus
Requires:       ros-melodic-sound-play
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-control-msgs
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-euscollada
BuildRequires:  ros-melodic-move-base-msgs
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-pr2-controllers-msgs
BuildRequires:  ros-melodic-pr2-description
BuildRequires:  ros-melodic-pr2-gazebo
BuildRequires:  ros-melodic-pr2-mechanism-msgs
BuildRequires:  ros-melodic-pr2-msgs
BuildRequires:  ros-melodic-robot-state-publisher
BuildRequires:  ros-melodic-roseus
BuildRequires:  ros-melodic-rosgraph-msgs
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-sound-play

%description
pr2eus

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Oct 01 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 0.3.14-3
- Autogenerated by Bloom

* Tue Oct 01 2019 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 0.3.14-2
- Autogenerated by Bloom

